name: Build and Push Docker Image

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          path: src

      - name: Set up versioning
        id: vars
        run: |
          GITHUB_SHA=${GITHUB_SHA::7}
          DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          TAG=$(date -u +"%Y.%m.%d.%H%M%S")
          echo "TAG=${TAG}" >> $GITHUB_OUTPUT
          echo "BUILD_DATE=${DATE}" >> $GITHUB_OUTPUT
          echo "GITHUB_SHA=${GITHUB_SHA}" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: src
          platforms: linux/amd64
          push: true
          tags: emergy/ptimer:latest,emergy/ptimer:${{ steps.vars.outputs.TAG }}
          build-args: |
            VERSION=${{ steps.vars.outputs.TAG }}
            BUILD_DATE=${{ steps.vars.outputs.BUILD_DATE }}
            GIT_COMMIT=${{ steps.vars.outputs.GITHUB_SHA }}
